---
- name: Expand file system and configure basic pi settings (e.g. hdmi off)
  hosts: initial
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: raspberry
  remote_user: root
  become: false
  roles:
    - role: geerlingguy.raspberry-pi 
    - role: mikolak.raspi-config
      raspi_config_update_packages: no
      raspi_config_expanded_filesystem: yes
      raspi_config_memory_split_gpu: 16
      raspi_config_ensure_optimal_cpu_params: yes
      locale: en_US.UTF8
      raspi_config_timezone: UTC
      raspi_config_hostname: heimbot
      raspi_config_enable_camera: no
      raspi_config_fail_on_auth_test: yes
      raspi_config_replace_user:
        name: tojo
        path_to_ssh_key: ~/.ssh/id_rsa.pub
